-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 17:34:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema index.html
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema index.html
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `index.html` DEFAULT CHARACTER SET utf8 ;
USE `index.html` ;

-- -----------------------------------------------------
-- Table `index.html`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`form` (
  `id_form` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `message` VARCHAR(500) NULL,
  `telephone` DECIMAL NULL,
  `subject` ENUM("billetterie", "organisation", "SAV", "remboursement") NULL,
  PRIMARY KEY (`id_form`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`event` (
  `id_event` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `date` VARCHAR(50) NULL,
  `hour` VARCHAR(45) NULL,
  `total_ticket_for_sale` DECIMAL NULL,
  `id_form` INT NOT NULL,
  `id_three_day_ticket` INT NOT NULL,
  PRIMARY KEY (`id_event`, `id_three_day_ticket`),
  INDEX `fk_event_form_idx` (`id_form` ASC) VISIBLE,
  CONSTRAINT `fk_event_form`
    FOREIGN KEY (`id_form`)
    REFERENCES `index.html`.`form` (`id_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`day_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`day_ticket` (
  `id_ticket_day` INT NOT NULL AUTO_INCREMENT,
  `stock_quantity` DECIMAL NULL,
  `price` DECIMAL NULL,
  PRIMARY KEY (`id_ticket_day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`two-day_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`two-day_ticket` (
  `id_two-day_ticket` INT NOT NULL AUTO_INCREMENT,
  `two-day_stock_quantity` DECIMAL NULL,
  `two_day_price` DECIMAL NULL,
  PRIMARY KEY (`id_two-day_ticket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`three_day_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`three_day_ticket` (
  `id_three_day_ticket` INT NOT NULL AUTO_INCREMENT,
  `three_day_ticket_stock_quantity` DECIMAL NULL,
  `three_day_price` DECIMAL NULL,
  PRIMARY KEY (`id_three_day_ticket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`event_has_three_day_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`event_has_three_day_ticket` (
  `event_id_event` INT NOT NULL,
  `event_three_day_ticket_id_three_day_ticket` INT NOT NULL,
  `id_three_day_ticket` INT NOT NULL,
  PRIMARY KEY (`event_id_event`, `event_three_day_ticket_id_three_day_ticket`, `id_three_day_ticket`),
  INDEX `fk_event_has_three_day_ticket_three_day_ticket1_idx` (`id_three_day_ticket` ASC) VISIBLE,
  INDEX `fk_event_has_three_day_ticket_event1_idx` (`event_id_event` ASC, `event_three_day_ticket_id_three_day_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_event_has_three_day_ticket_event1`
    FOREIGN KEY (`event_id_event` , `event_three_day_ticket_id_three_day_ticket`)
    REFERENCES `index.html`.`event` (`id_event` , `id_three_day_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_three_day_ticket_three_day_ticket1`
    FOREIGN KEY (`id_three_day_ticket`)
    REFERENCES `index.html`.`three_day_ticket` (`id_three_day_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`event_has_two-day_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`event_has_two-day_ticket` (
  `event_id_event` INT NOT NULL,
  `event_id_three_day_ticket` INT NOT NULL,
  `id_two-day_ticket` INT NOT NULL,
  PRIMARY KEY (`event_id_event`, `event_id_three_day_ticket`, `id_two-day_ticket`),
  INDEX `fk_event_has_two-day_ticket_two-day_ticket1_idx` (`id_two-day_ticket` ASC) VISIBLE,
  INDEX `fk_event_has_two-day_ticket_event1_idx` (`event_id_event` ASC, `event_id_three_day_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_event_has_two-day_ticket_event1`
    FOREIGN KEY (`event_id_event` , `event_id_three_day_ticket`)
    REFERENCES `index.html`.`event` (`id_event` , `id_three_day_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_two-day_ticket_two-day_ticket1`
    FOREIGN KEY (`id_two-day_ticket`)
    REFERENCES `index.html`.`two-day_ticket` (`id_two-day_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `index.html`.`event_has_day_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `index.html`.`event_has_day_ticket` (
  `event_id_event` INT NOT NULL,
  `event_id_three_day_ticket` INT NOT NULL,
  `id_ticket_day` INT NOT NULL,
  PRIMARY KEY (`event_id_event`, `event_id_three_day_ticket`, `id_ticket_day`),
  INDEX `fk_event_has_day_ticket_day_ticket1_idx` (`id_ticket_day` ASC) VISIBLE,
  INDEX `fk_event_has_day_ticket_event1_idx` (`event_id_event` ASC, `event_id_three_day_ticket` ASC) VISIBLE,
  CONSTRAINT `fk_event_has_day_ticket_event1`
    FOREIGN KEY (`event_id_event` , `event_id_three_day_ticket`)
    REFERENCES `index.html`.`event` (`id_event` , `id_three_day_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_has_day_ticket_day_ticket1`
    FOREIGN KEY (`id_ticket_day`)
    REFERENCES `index.html`.`day_ticket` (`id_ticket_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
